# Generated by Django 4.2.1 on 2023-05-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="area_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="city",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="company_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_type", models.CharField(max_length=50)),
                ("company_address", models.TextField()),
                ("company_webiste", models.CharField(max_length=50)),
                ("founded_year", models.IntegerField()),
                ("company_support_mail", models.EmailField(max_length=254)),
                ("company_support_phone", models.IntegerField()),
                ("company_size", models.IntegerField()),
                ("company_city", models.CharField(default="", max_length=50)),
                ("company_area", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=254)),
                ("comment", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="feedbackpagesubmit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=254)),
                ("comment", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="login_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("phone_no", models.IntegerField()),
                ("dp", models.ImageField(upload_to="photos")),
                ("password", models.CharField(default="admin", max_length=300)),
                ("Role", models.CharField(max_length=100)),
                (
                    "Status",
                    models.CharField(
                        choices=[(0, "inactive"), (1, "active")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="skills_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="state_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="university_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="user_skill_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_level", models.IntegerField(default=25)),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.login_table",
                    ),
                ),
                (
                    "skill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.skills_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_detail_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("dob", models.DateField()),
                ("address", models.TextField()),
                (
                    "area_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.area_table",
                    ),
                ),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.city"
                    ),
                ),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.login_table",
                    ),
                ),
                (
                    "state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.state_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="resume_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="file")),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.login_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="requirement_jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=35)),
                ("job_description", models.TextField()),
                ("vacancy", models.IntegerField()),
                ("basic_pay", models.IntegerField()),
                ("date", models.DateField(auto_now=True)),
                ("time", models.TimeField(auto_now=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")], max_length=10
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.company_details",
                    ),
                ),
                (
                    "job_skill",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.skills_table",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company_details",
            name="l_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.login_table"
            ),
        ),
        migrations.CreateModel(
            name="college_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=25)),
                (
                    "university_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.university_table",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="state_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.state_table"
            ),
        ),
        migrations.CreateModel(
            name="branch_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=25)),
                (
                    "college_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.college_table",
                    ),
                ),
                (
                    "university_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.university_table",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area_table",
            name="city_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.city"
            ),
        ),
        migrations.AddField(
            model_name="area_table",
            name="state_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.state_table"
            ),
        ),
        migrations.CreateModel(
            name="appliedjob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_datetime", models.DateTimeField(auto_now=True)),
                (
                    "applied_job_status",
                    models.CharField(
                        choices=[
                            ("Under Review", "Under Review"),
                            ("Shown Interest", "Shown Interest"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Under Review",
                        max_length=50,
                    ),
                ),
                ("show_interest_button", models.BooleanField(default=True)),
                ("rejected", models.BooleanField(default=False)),
                (
                    "applied_company_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.company_details",
                    ),
                ),
                (
                    "applied_job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requirement_jobs",
                    ),
                ),
                (
                    "candidate_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_detail_table",
                    ),
                ),
                (
                    "candidate_resume",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.resume_table",
                    ),
                ),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.login_table",
                    ),
                ),
            ],
        ),
    ]
