# Generated by Django 4.2.1 on 2023-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_detail_table",
            name="Enrollment",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="user_detail_table",
            name="passoutyear",
            field=models.IntegerField(default=2020),
        ),
    ]
