# Generated by Django 4.2.1 on 2023-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_user_detail_table_enrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement_jobs",
            name="job_skill",
            field=models.CharField(default="", max_length=35),
        ),
    ]
